site_name: NBility
site_url: https://nbility.netbeheernederland.nl/
repo_url: https://github.com/NBility-Model/nbility-model.github.io
edit_uri: edit/main/docs/
theme:
  name: material
  features:
    - content.action.edit
  palette:
    primary: white
  language: en
  font:
    text: Poppins
  logo: assets/logo.svg
  favicon: assets/favicon.png
extra_css:
  - stylesheets/extra.css
